### PR TITLE
GDI+ load font from memory

### PR DESCRIPTION
**Pull request by DeXP**
There is new user function: `nk_gdipfont_create_mem`. Added `fontCollection` member to `gdip` structure to automatically clean it up at execution end.

Added 1px overlap near filled pies. There is no empty space between pie and rectangle now. It was especially conspicuous on red theme.

### CODE REVIEW

**Comment by DeXP** [comment]
PR: My article about Nuklear on Habrahabr (Russian only, sorry):
https://habrahabr.ru/post/319106/

**Comment by dumblob** [comment]
@DeXP nice article! Just curious, will there be any follow-up with advanced examples and/or quirks?

**Comment by vurtun** [comment]
Thanks for the PR and nice article, at least what I can get out of google translation sounds good.

**Comment by DeXP** [comment]
@dumblob Why not? I'm planning to use Nuklear in my own small projects. New projects = new skills, new features, new pull requests.

**Pull request merged**
