### PR TITLE
SDL software rendered

### PR DESCRIPTION
**Pull request by slvtmn**
SDL software rendered 
Dependence on TTF_Font.h and SDL.h

### CODE REVIEW

**Comment by mmozeiko** [comment]
I don't think this its accurate to call this "software rendered". SDL_Renderer is GPU backed renderer. It uses OpenGL, D3D or similar API to do actual rendering. The documentation is pretty clear on this: https://wiki.libsdl.org/CategoryRender

**Comment by vurtun** [comment]
In addition to what @mmozeiko said. I also noticed that a number of primitives cannot be drawn directly by SDL and the coding style is completely off. So I am a little bit hesitant to add this demo backend. I now have three SDL demo backends which should be enough.

**Comment by hbiblia** [comment]
Seria muy bueno que nuklear tenga soporte a SDL2 con SDL_Rendered

**Comment by hbiblia** [comment]
Estoy trabajando en Nuklear SDL_Native - https://github.com/hbiblia/nuklear/tree/master/demo/sdl_native

**Comment by hbiblia** [comment]
Yo también estoy trabajando en algo similar - [SDL2_Native](https://github.com/hbiblia/nuklear/tree/master/demo/sdl_native)

**Pull request closed without merging**
