### PR TITLE
Add nk_***_get_scroll and nk_***_set_scroll for groups, windows, and popups

### PR DESCRIPTION
**Pull request by keharriso**
I thought these two functions (`nk_group_get_scroll` and `nk_group_set_scroll`) would be useful. I also added similar functions for windows and popups.

### CODE REVIEW

**Comment by keharriso** [comment]
This PR would help #783 and #326, and would help greatly with the LÖVE bindings I maintain.

**Comment by dumblob** [comment]
Hi, could you also bump the version accordingly?

**Comment by keharriso** [comment]
Did I do that right?

**Comment by keharriso** [comment]
I'm going to close this so I can split the pull request in two.

**Pull request closed without merging**
