### PR TITLE
SFML OpenGL2 and OpenGL3 backend

### PR DESCRIPTION
**Pull request by ricanteja**
Hi, I'm that guy from twitter that shared this pic
alt text

I've started working on getting Nuklear a SFML/OpenGL renderer. Right now I'm starting out with OpenGL2 since that is what I'm most familiar with and there are a couple of demos I can take notes from.

Right now I'm having some issues with incorrect drawing of windows (as can be seen in the screenshot). I was going to open an issue for this but thought that since I'm going to make a pull request later on that I should just roll both into one and see if I can get this issue solved and pulled all in one.

### CODE REVIEW

**Comment by vurtun** [comment]
From a quick glance could the missing window be a clipping bug? In every new frame I assume the whole screen can be drawn into until I push the first clipping rectangle inside the window. So if another scissor rectangle is set at the beginning of the frame the window background will not be drawn.

**Comment by ricanteja** [comment]
Thanks for replying. As far as I can tell sf::Window does not have any hidden calls to glScissor.

**Comment by ricanteja** [comment]
Fixed the issue will alter the pull request later tonight. Now I got a new issue which is text input crashes for some reason.

**Comment by ricanteja** [comment]
Fixed the clipping bug.
Fixed the text input crash bug.

I'll start working on the SFML Drawables and SFML OpenGL3 backends next.

**Comment by ricanteja** [comment]
I've pretty much finished the code. I'm just working on packaging and writing a half decent Makefile people can use on their own system with minimal editing if needed. If you got any advice I'd welcome it.

**Comment by vurtun** [comment]
Feel free to tell me whenever I should pull it.

**Comment by ricanteja** [comment]
Thanks. I'll be letting you know later this day I think.

**Comment by ricanteja** [comment]
Just pushed a new commit but I'm not ready to merge yet.

I've been working for hours trying to fix a bug that has been driving me nuts. All widgets work except for some stuff that can't be done currently because SFML lacks the functionality (clipboard support). There is just one problem now. When interacting with the property bar that says "Compression"; if you move mouse fast left or right, as long as the widget hasn't reached a limit of 0 or 100, and you release your left mouse button while you are moving, the moue cursor will teleport, usually up and to the left. It is driving me near mad so I've come to ask for help here.

Other than that the Makefiles are all set. I have tested and can confirm it works on both Windows and Linux.

I have attatched a gif showing the issue. Maybe you've seen this before?
alt text

**Comment by ricanteja** [comment]
Fixed the last bug and added the Readme files.

I'm ready to merge when you are!

I'm going to go bug the SFML people now to implement Clipboard support. Once that is done I'll be making a new pull request.

**Pull request merged**
