### PR TITLE
GDI+ simplified image loading, added error checking and image freeing

### PR DESCRIPTION
**Pull request by mmozeiko**
This simplifies GDI+ image loading, adds error checking to image loading functions, and adds missing nk_gdip_image_free function to free loaded image.

### CODE REVIEW

**Comment by dumblob** [comment]
Maybe there should be a comment, that `shwapi` requires Service Pack 2 on WinXP and is not guaranteed to work on and I quote "in subsequent versions of Windows" ([Deprecated API > SHLWAPI Wrapper Functions](https://msdn.microsoft.com/en-us/library/windows/desktop/bb759845(v=vs.85).aspx )). Or maybe we shouldn't use `shwapi` at all.

**Comment by paulsapps** [comment]
SHCreateMemStream is not one of the depcreated functions https://msdn.microsoft.com/en-us/library/windows/desktop/bb773831(v=vs.85).aspx

**Comment by vurtun** [comment]
Thanks @mmozeiko, @dumblob and @paulsapps I checked and could not find any reference that `SHCreateMemStream` is deprecated and the resulting code looks a lot cleaner so I will pull this.

**Comment by DeXP** [comment]
Can't compile it under GCC, both native and crosscompilation.
```
/usr/bin/i686-w64-mingw32-g++ -o Wordlase.exe @"WordGame.txt" -L. -lgdiplus -lshlwapi -mwindows -s
(.text$nk_gdip_load_image_from_memory+0x1a): undefined reference to `SHCreateMemStream'
```
File `/usr/i686-w64-mingw32/lib/libshlwapi.a` contains symbols, related to `SHCreateMemStream`

GCC info:
```
$ /usr/bin/i686-w64-mingw32-gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/i686-w64-mingw32-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-w64-mingw32/7.1.1/lto-wrapper
Target: i686-w64-mingw32
Configured with: /build/mingw-w64-gcc/src/gcc/configure --prefix=/usr --libexecdir=/usr/lib --target=i686-w64-mingw32 --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-threads=posix --enable-fully-dynamic-string --enable-libstdcxx-time=yes --with-system-zlib --enable-cloog-backend=isl --enable-lto --disable-dw2-exceptions --enable-libgomp --disable-multilib --enable-checking=release
Thread model: posix
gcc version 7.1.1 20170516 (GCC)
```
GCC 7.2.0 was used under Windows. The result is the same - undefined reference.

**Comment by mmozeiko** [comment]
What kind of gcc you are using on Windows?

For me it compiles fine with gcc from msys2. This is how I compile in `demo\gdip` folder:
```
i686-w64-mingw32-gcc.exe main.c -lgdiplus -lshlwapi -mwindows
```

gcc version:
```
Using built-in specs.
COLLECT_GCC=C:\msys2\mingw32\bin\gcc.EXE
COLLECT_LTO_WRAPPER=C:/msys2/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.1.0/lto-wrapper.exe
Target: i686-w64-mingw32
Configured with: ../gcc-7.1.0/configure --prefix=/mingw32 --with-local-prefix=/mingw32/local --build=i686-w64-mingw32 --host=i686-w64-mingw32 --target=i686-w64-mingw32 --with-native-system-header-dir=/mingw32/i686-w64-mingw32/include --libexecdir=/mingw32/lib --enable-bootstrap --with-arch=i686 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw32 --with-mpfr=/mingw32 --with-mpc=/mingw32 --with-isl=/mingw32 --with-pkgversion='Rev2, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld --disable-sjlj-exceptions --with-dwarf2
Thread model: posix
gcc version 7.1.0 (Rev2, Built by MSYS2 project)
```

On Linux it seems that older MinGW version are missing SHCreateMemStream declaration in header (did  you get warning about implicit declaration of this function?). So compiler doesn't mangle symbol correctly for stdcall ABI. It was added in January of 2017: https://sourceforge.net/p/mingw-w64/mingw-w64/ci/835affee01d5f1ccd593ea5a28489ba696375e30/ Check if you can upgrade to newer version of mingw toolchain on your Linux. 

If you cannot or doesn't help, then you can simply add this declaration yourself in nuklear_gdip.h header. Just put following line somewhere in beginning of this header:
```
LWSTDAPI_(IStream *) SHCreateMemStream(const BYTE *pInit, _In_ UINT cbInit);
```

**Comment by DeXP** [comment]
Yep, declaration really helped, thanks. Maybe add it to master `nuklear_gdip.h` sources?

**Pull request merged**
