### PR TITLE
fix compiling error on OSX (-lglfw3 not found)

### PR DESCRIPTION
**Pull request by jwdeitch**
After brew install:
error: ld: library not found for -lglfw3

### CODE REVIEW

**Comment by vurtun** [comment]
Thanks for the PR,
can somebody please confirm that it works correctly? I don't have OSX so cannot test it.

**Comment by lieff** [comment]
It's brew version dependent. On my local macbook with newer brew I use -lglfw (after brew install glfw), with Travis CI, I'm forced to use -lglfw3 after same install command.

**Comment by valera-rozuvan** [comment]
This works for me. To be able to use this on a fresh Mac OS, you first need to install some pre-requisites:

```
xcode-select --install
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install glew
brew install glfw3
brew install pkg-config
```

Please merge this PR!

**Comment by valera-rozuvan** [comment]
Without this PR, I have the following error:

screen shot 2017-09-18 at 12 05 32 pm

**Pull request merged**
