### PR TITLE
Add software rasterizer library and demo.

### PR DESCRIPTION
**Pull request by siro20**
Add software rasterizer library and demo.
The software rasterizer is to be used with raw framebuffer
devices, where no GPU or X11 is available.
The demo emulates a raw framebuffer on X11 using XShmImage / XImage.
Fonts are rendered software only using nearest filtering.

Tested:
The library has been tested on Lenovo Thinkpad T500 and is able to render more than 30fps on a single core with no further optimizations and VSNYC enabled.

TODO:
Improve font rendering by using filters.
Window resizing isn't supported by the X11 demo application.

Signed-off-by: Patrick Rudolph <siro@das-labor.org>

### CODE REVIEW

**Comment by dumblob** [comment]
Thanks for splitting it into two commits.

I finally took a closer look and it seems the code needs some love. First I tried to track down why the dimension of the buffer can't be changed in runtime dynamically and didn't find any obstacles - it would require just decoupling from the initialization functions and otherwise everything shall work. So I definitely agree with the TODO item `Window resizing isn't supported by the X11 demo application`.

Second thing is e.g. the `nk_rawfb_render()` function using a global variable. Globals definitely shouldn't be anywhere (I didn't check for other occurrences, but I'll do it once the code settles down a bit) and instead usual function arguments should be the way to go. Also it would be nice to mark API functions with information about thread safety (nearly everything seemed safe, but again, I didn't do any deep analysis).

**Comment by siro20** [comment]
I've made it thread safe by using a context instead a static object.
I fixed the dynamic resize.
Added a comment about thread safety.

**Comment by dumblob** [comment]
@siro20 thanks.

I'm currently out of time and will get back to this first in about two months :cry:. In the mean time anybody can do a review to open the path to the mainline :wink:.

**Comment by vurtun** [comment]
Hey @siro20,
I went over, read and run your code. Looks really nice I like it. However I noticed a few issues. Could you please change the coding style to match closer to nuklear ( `{`  always on same line except for functions and `if` with only one expression don't have any `{}` at all). Second and more important issue is a clipping bug I found. If you run the `overview.c` UI and scroll, the clipping rect seems to be off. Especially visible  for  input boxes:

clipping

**Comment by siro20** [comment]
I fixed the following points:
* Use nuklear's coding style
* Fixed clipping bug

**Comment by vurtun** [comment]
Style looks OK, there are still some style issue by I can change these by myself. However while the lower window clipping rectangle seems to work now the upper clipping bounds seems to be bugged:

bug

**Comment by siro20** [comment]
Fixed upper scissors
Added support for text scissors

**Pull request merged**
