### PR TITLE
works on MinGW

### PR DESCRIPTION
**Pull request by yinqiang**

### CODE REVIEW

**Comment by vurtun** [comment]
OK I am not quite sure since I do not have a windows system but is is it really required for mingw to use shader version 150, this seems really unlikely to me? Before I pull this I want at least conformation from others to make sure this is really what mingw requires.

**Comment by lieff** [comment]
I think it's heavily depended on mingw installation, because mingw itself do not have glew etc.
Only more or less "standard" way for windows is MSYS2 with packman. I tried latest msys2 x64 and cannot confirm it works:
```
>pacman -Su mingw64/mingw-w64-x86_64-glew mingw64/mingw-w64-x86_64-glfw mingw64/mingw-w64-x86_64-freeglut make

>make CFLAGS=-I../../../../mingw64/include
rm -f bin/node_editor
cc -I../../../../mingw64/include -o bin/node_editor node_editor.c -mwindows -lglfw3 -lopengl32 -lm -lGLU32 -lGLEW32
In file included from ../../../../mingw64/include/GL/glew.h:1202:0,
                 from node_editor.c:24:
/usr/include/w32api/GL/glu.h:68:79: error: expected ‘)’ before ‘*’ token
 void APIENTRY gluQuadricCallback(GLUquadric *qobj,GLenum which,void (CALLBACK *fn)());
                                                                               ^
/usr/include/w32api/GL/glu.h:78:79: error: expected ‘)’ before ‘*’ token
 void APIENTRY gluTessCallback(GLUtesselator *tess,GLenum which,void (CALLBACK *fn)());
```
CFLAGS=-I../../../../mingw64/include needed because normally pkg-config must be used for glfw\glew:
```
pkg-config --cflags glew
-I/mingw64/include
```

**Comment by yinqiang** [comment]
Thank you for review.
This is not compile issue, but runtime assertion failed.

If use lines like:
33:  //#if defined(__APPLE__) || defined(__MINGW32__)
34:  #if defined(__APPLE__)
35:    #define NK_SHADER_VERSION "#version 150\n"
36:  #else
37:    #define NK_SHADER_VERSION "#version 300 es\n"
38:  #endif
...
77:    glGetShaderiv(dev->vert_shdr, GL_COMPILE_STATUS, &status);
78:    assert(status == GL_TRUE);

Will get result:
Assertion failed!
File: nuklear_glfw.c
Line: 78
Expreesion: status == GL_TRUE

Use code line 33 just fine.

OS: Win7 32bits
MinGW: MINGW32_NT-6.1
GLEW: glew-1.13.0, local mingw compiled.

**Comment by lieff** [comment]
It's issue with glu.h on my old msys installation. I do full reinstall with upgrade instruction from here https://msys2.github.io/

And it compiles.

**Comment by fr500** [comment]
It's working fine on an up to date msys2 installation without this PR

**Comment by vurtun** [comment]
OK as far as it looks to me this PR is not required and I will close it to keep things as simple as possible. Still thanks @yinqiang for your PR, time and work. Same for the others thanks for testing!

**Pull request closed without merging**
